name = "scheduled"
main = "src/worker.js"
compatibility_date = "2024-11-20"
workers_dev = false
preview_urls = false

[placement]
mode = "smart"

[triggers]
crons = [ "0 9 * * *" ]

[[services]]
binding = "EMAIL_SERVICE"
service = "email"
environment = "production"
entrypoint = "EmailWorker"

[[kv_namespaces]]
id = "f4e4b4cb205d4329a955a7223f61b29e"
binding = "MISC"
